In [25]:
#Write a function so that the columns of the output matrix are powers of the input vector
import numpy as np
def vandermonde(a,k):
    c=[]
    a=list(map(int,a))
    b=np.array(a)
    for i in range(k-1,-1,-1):
        c.extend(list(b**i))
    c=np.array(c).reshape(k,len(a)).transpose()
    return c
test=input("Enter list of numbers seperated by comma: ").split(",")
k=int(input("enter value of k in integer: "))
print(vandermonde(test,k if k>1 else len(test)))

Enter list of numbers seperated by comma: 2,3,5,7,11
enter value of k in integer: 0
[[   16     8     4     2     1]
 [   81    27     9     3     1]
 [  625   125    25     5     1]
 [ 2401   343    49     7     1]
 [14641  1331   121    11     1]]


In [32]:
#Program to find moving average
list1=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100,150])
k=moving_average=3
print("Length of list is:",len(list1))
print("The moving average sequence has",len(list1)-k+1,"elements")
for i in range(0,len(list1)-k+1):
    print("Result",i+1,"is",np.average(list1[i:moving_average]))
    moving_average=moving_average+1

Length of list is: 13
The moving average sequence has 11 elements
Result 1 is 5.0
Result 2 is 4.666666666666667
Result 3 is 5.666666666666667
Result 4 is 6.666666666666667
Result 5 is 9.666666666666666
Result 6 is 28.666666666666668
Result 7 is 49.333333333333336
Result 8 is 72.66666666666667
Result 9 is 84.0
Result 10 is 93.33333333333333
Result 11 is 116.33333333333333
